Workbench v1:
  project-link:
  github-repo: jarranpedersenfreelance/Workbench
  status: Complete
Mayaglyphs:
  project-link: https://mayaglyphs.org
  github-repo: jarranpedersenfreelance/Mayaglyphs
  status: In-Progress
Agent:
  project-link:
  github-repo: jarranpedersenfreelance/Agent
  status: In-Progress
Workbench v2:
  project-link:
  github-repo: jarranpedersenfreelance/Workbench-v2
  status: In-Progress